### ISSUE TITLE
撤销 功能有时会失效，ctrl z 按钮无法控制撤销

### ISSUE THREAD

**Issue by anime777** [nihaojob/vue-fabric-editor#1]
1.撤销 功能有时会失效，
2. ctrl z 按钮无法控制撤销

**Comment by nihaojob** [comment]
> 1.撤销 功能有时会失效，
> 2. ctrl z 按钮无法控制撤销

感谢反馈，快捷键后退的功能暂时还没开发，如果你感兴趣或者有时间的话，可以一起开发一下🙆，让快捷键模块和历史模块联动一下。

**Comment by nihaojob** [comment]
#8 https://github.com/nihaojob/vue-fabric-editor/pull/8 已经更新功能，感谢 @QJune 提交的代码。
