### ISSUE TITLE
国际化遗漏字段问题

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#124]
https://github.com/nihaojob/vue-fabric-editor/pull/123

![image](https://user-images.githubusercontent.com/13534626/224605758-eca42b1c-a901-49c6-a648-80091db72a8f.png)

**Comment by nihaojob** [comment]
https://i18ns.com/zh/index.html

**Comment by makeng** [comment]
1. 编组方式，遵照《重构》中“去除中间数据”的原则，方便组织和维护。
2. 支持 Inlay Hints 的 IDE 下，形式类似表格
<img width="514" alt="image" src="https://user-images.githubusercontent.com/23654388/224991048-c285ce38-4a13-45b8-aebc-5c0d8056937a.png">
3. 库大多数都是用 json 管理方式，但目的是动态加载语言包，维护性为其次。
4. 在主要 issue 解决后，再考虑加入此功能，并方案修改为以 Excel 代替 json。

**Comment by nihaojob** [comment]
感谢大佬提炼总结  👍，期待后期一起维护
