### ISSUE TITLE
能否增加流程线那种，动态流动的线

### ISSUE THREAD

**Issue by make-dream** [nihaojob/vue-fabric-editor#125]
![image](https://user-images.githubusercontent.com/20986400/224883989-661a2f11-2810-43cb-bf92-acf0572a2f1b.png)
类似这种流动的虚线

**Comment by nihaojob** [comment]
> ![image](https://user-images.githubusercontent.com/20986400/224883989-661a2f11-2810-43cb-bf92-acf0572a2f1b.png) 类似这种流动的虚线

我能想到的方式是动态修改元素的边框来实现，不知道你有没有更好的方法。
![2023-03-14 18 31 24](https://user-images.githubusercontent.com/13534626/224973594-81c58ca4-5295-4a4b-a86d-275fec6bed16.gif)

**Comment by nihaojob** [comment]
![image](https://user-images.githubusercontent.com/13534626/225517064-24758802-78a3-4ceb-9c14-add3dcc50cdd.png)

**Comment by hhzhldhjl** [comment]
实现了吗？我也想实现这种效果

**Comment by nihaojob** [comment]
@hhzhldhjl  @make-dream 星球内已经给出了2中实现思路的Demo。
![Fs92OcmBFhLDpVO8NR29ws87x6Y8](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/baaac4d0-f358-4afd-8840-3b230d0fcc84)
![FvMUwNFA8aAc3bRixQ_J7w8B-4SH](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/df9cb311-abec-4b2b-9601-8f2c28bace91)
