### ISSUE TITLE
开发 vue3渐变组件

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#126]
参考脚手架：https://github.com/Jacobs63/vue3-tabs-component

**Comment by Qiu-Jun** [comment]
之前群里发你的vue-color-gradient-picker这个渐变组件的v3版(vue3-color-gradient-picker)不合适吗= =

**Comment by nihaojob** [comment]
> 之前群里发你的vue-color-gradient-picker这个渐变组件的v3版(vue3-color-gradient-picker)不合适吗= =

功能没有目前的完整，缺少径向渐变的功能，反正后期要用，也要尝试下vue3，准备自己搞一个。

**Comment by Qiu-Jun** [comment]
> vue-color-gradient-picker

我有空帮你把这个vue-color-gradient-picker换v3语法

**Comment by nihaojob** [comment]
> > vue-color-gradient-picker
> 
> 我有空帮你把这个vue-color-gradient-picker换v3语法

太好了，我在找合适的脚手架，在github主页有一个vue3的分类，你看看有没有合适的

**Comment by Qiu-Jun** [comment]
> > > vue-color-gradient-picker
> > 
> > 
> > 我有空帮你把这个vue-color-gradient-picker换v3语法
> 
> 太好了，我在找合适的脚手架，在github主页有一个vue3的分类，你看看有没有合适的

脚手架我都是自己弄的- -

**Comment by Qiu-Jun** [comment]
> > > vue-color-gradient-picker
> > 
> > 
> > 我有空帮你把这个vue-color-gradient-picker换v3语法
> 
> 太好了，我在找合适的脚手架，在github主页有一个vue3的分类，你看看有没有合适的

到时候我会打包发布到npm, 你现在怎么用，到时就怎么用就可以了

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/a929ad821944d0be9edfd24d4891a5007804c57b
@Qiu-Jun  感谢老弟的付出，readme中已署名，vue3已合并到主分支。
