### ISSUE TITLE
demo打开空白页

### ISSUE THREAD

**Issue by sosel** [nihaojob/vue-fabric-editor#128]
还有其他同学的参考一下吗？好像安装教程很少，有详细安装教程吗，或者有视频吗？

**Comment by nihaojob** [comment]
> 还有其他同学的参考一下吗？好像安装教程很少，有详细安装教程吗，或者有视频吗？

构建后有些问题，如果预览可以先本地跑一下，我最近修复下打包的问题

**Comment by nihaojob** [comment]
已修复  感谢反馈
