### ISSUE TITLE
无法保存透明背景

### ISSUE THREAD

**Issue by s97712** [nihaojob/vue-fabric-editor#130]
背景设置为透明，保存后的图片不是透明的

**Comment by nihaojob** [comment]
![image](https://user-images.githubusercontent.com/13534626/230528359-94bc3e8f-23a2-4f64-9cbe-e72fa169bb26.png)
有大佬提供解决方案，后期会修复。

**Comment by nihaojob** [comment]
![image](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/cd2754d0-6cdc-4048-983f-ce24b8bc708a)

https://github.com/nihaojob/vue-fabric-editor/commit/834ad92bffeea08aa2cccb4f70139daace40bf2b
