### ISSUE TITLE
图标字体文件缺失，图标显示不了

### ISSUE THREAD

**Issue by tsheng** [nihaojob/vue-fabric-editor#134]
fonts/ionicons.woff2?v=3.0.0 访问报404，页面上的所有图标显示不全。

**Comment by nihaojob** [comment]
感谢大佬反馈，希望可以提供具体的复现步骤和更详细报错信息，根据这些信息没办法定位。

**Comment by tsheng** [comment]
直接clone下来，运行命令：yarn install && yarn serve就是这样的，看network上的请求信息是这样的：

Request URL: http://localhost:5173/fonts/ionicons.woff2?v=3.0.0
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:5173
Referrer Policy: strict-origin-when-cross-origin

**Comment by tsheng** [comment]
> 感谢大佬反馈，希望可以提供具体的复现步骤和更详细报错信息，根据这些信息没办法定位。

下载github上的demo页面也是这样的了 😭 https://nihaojob.github.io/vue-fabric-editor/#/
