### ISSUE TITLE
支持垂直文字显示

### ISSUE THREAD

**Issue by slarkerino** [nihaojob/vue-fabric-editor#146]
请问下如何实现文字垂直竖着显示

**Comment by nihaojob** [comment]
http://fabricjs.com/text-on-paths  可以看下这个，邀请你加入微信交流群哈  vx：13146890191

**Comment by nihaojob** [comment]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/13534626/230531549-72262784-d612-47f6-b2da-d2d965b8d190.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/13534626/230531555-5c00d927-89e1-431f-8051-bdc4de9da56b.png">
