### ISSUE TITLE
导入JSON后setSize.vue不会根据新导入的workspace大小变化

### ISSUE THREAD

**Issue by slarkerino** [nihaojob/vue-fabric-editor#154]
![image](https://user-images.githubusercontent.com/7014849/230858813-2cfa5026-b17b-4319-99c3-1fd303dec0b3.png)
![image](https://user-images.githubusercontent.com/7014849/230858889-f4a529b0-e3db-4f1a-aa9f-a3b490258bb6.png)

**Comment by nihaojob** [comment]
收到 感谢大佬 有时间就修复

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/9393a7126edbcb752ae10174b6a51c973ab11574
