### ISSUE TITLE
单元测试选型与接入

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#159]

**Comment by dulltackle** [comment]
[Vitest](https://vitest.dev/) 或许是一个不错的选择?

1. 直接由 Vite 驱动, 比如在 Vite 配置好了 `alias` 别名, Vitest 可以直接用
2. Vue 文档[首推](https://vuejs.org/guide/scaling-up/testing.html#recommendation)的测试框架, Vue 本身也[迁移](https://github.com/vuejs/core/blob/main/vitest.config.ts)到 Vitest 了
3. 和老牌测试框架 [Jest](https://vitest.dev/guide/features.html#chai-and-jest-expect-compatibility) 兼容

---

个人觉得项目当前在做"组件向组合式 setup 迁移"工作的话, 引入单元测试框架更是应该尽快, 因为:

- 可以说定组件的功能: 没过测试的话就说明迁移之后的组合式 setup 组件缺失了功能
- 可以减轻维护压力: 组件的测试过了可以佐证关键功能没有问题, 这部分对应的代码可以相对略看
- 可以让维护者和参与者交流更流畅: 参与者可以通过提交**测试文件PR**来说明意图(用代码交流或许比说话更清晰😝)

**Comment by nihaojob** [comment]
> [Vitest](https://vitest.dev/) 或许是一个不错的选择?
> 
> 1. 直接由 Vite 驱动, 比如在 Vite 配置好了 `alias` 别名, Vitest 可以直接用
> 2. Vue 文档[首推](https://vuejs.org/guide/scaling-up/testing.html#recommendation)的测试框架, Vue 本身也[迁移](https://github.com/vuejs/core/blob/main/vitest.config.ts)到 Vitest 了
> 3. 和老牌测试框架 [Jest](https://vitest.dev/guide/features.html#chai-and-jest-expect-compatibility) 兼容
> 
> 个人觉得项目当前在做"组件向组合式 setup 迁移"工作的话, 引入单元测试框架更是应该尽快, 因为:
> 
> * 可以说定组件的功能: 没过测试的话就说明迁移之后的组合式 setup 组件缺失了功能
> * 可以减轻维护压力: 组件的测试过了可以佐证关键功能没有问题, 这部分对应的代码可以相对略看
> * 可以让维护者和参与者交流更流畅: 参与者可以通过提交**测试文件PR**来说明意图(用代码交流或许比说话更清晰😝)

感谢你的建议，之前调研过Vitest，也在纠结用jest 还是用 vitest，你的建议给了我信息， 我正在做插件化的改造，我将尝试在插件化改造中引入vitest，感兴趣的话 欢迎一起维护。

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/380
