### ISSUE TITLE
大佬能否整个vue3版本的出来😁

### ISSUE THREAD

**Issue by asang28** [nihaojob/vue-fabric-editor#16]

**Comment by nihaojob** [comment]
> _No description provided._

其实有意向升级的，不知道大佬有没有精力一起搞一下呀？ 哈哈，可以先把脚手架升级了，再改造组件内部方法。

**Comment by sww1740747758** [comment]
最近可能没有时间，大佬先着手，后续我有时间参与进来。哈哈

**Comment by icleitoncosta** [comment]
I can help with that migration. From what I understand they want to carry out the entire project migration to Vue3, right?

**Comment by icleitoncosta** [comment]
> Yes, can you set up the scaffold first? Later, I can participate in the transformation when I am free

I will work on it

**Comment by sww1740747758** [comment]
> > Yes, can you set up the scaffold first? Later, I can participate in the transformation when I am free
> 
> I will work on it

Look forward to your release of the first edition

**Comment by nihaojob** [comment]
> > > 是的，你能先搭好脚手架吗？以后有空可以参与改造
> > 
> > 
> > 我会努力的
> 
> 期待您发布第一版

感谢各位大佬，可以直接搞一个分支，在现有基础上升级感觉会方便一些，工作流也少。

**Comment by nihaojob** [comment]
> > Yes, can you set up the scaffold first? Later, I can participate in the transformation when I am free
> 
> I will work on it

Hi，Welcome to participate，My English is poor，Create a new branch and Migration to  vue3   Is it better? https://v3-migration.vuejs.org/

**Comment by icleitoncosta** [comment]
> > > Yes, can you set up the scaffold first? Later, I can participate in the transformation when I am free
> 
> > 
> 
> > I will work on it
> 
> 
> 
> Hi，Welcome to participate，My English is poor，Create a new branch and Migration to  vue3   Is it better? https://v3-migration.vuejs.org/

Thank you, I've done this migration before and from what I saw in the code it's easy to do, it's well organized. During the week I will create the branch and do that.

**Comment by icleitoncosta** [comment]
Hello, I started the migration to Vue3, however, right away, I already had a problem.
The view-design library doesn't support vue3, only vue1 or vue2, do you have any suggestions of what we can use to replace it?

**Comment by sww1740747758** [comment]
> Hello, I started the migration to Vue3, however, right away, I already had a problem. The view-design library doesn't support vue3, only vue1 or vue2, do you have any suggestions of what we can use to replace it?

I looked at the code, and it was true. Personally, I suggest you consider upgrading with element-plus. I hope so. But we still need to discuss with the author

**Comment by icleitoncosta** [comment]
> There is time difference between us, and communication may not be timely.

Yes, I think element-plus will work well, I didn't know about it yet.

Exactly, I'm from Brazil, and I can only move at night, after leaving work, so there will always be this delay in the response, but I believe that this upgrade will be quick, among other adjustments that we can make together.

I don't know if the project has a Telegram channel, if so, we can discuss the project there.

**Comment by sww1740747758** [comment]
> 

I also agree that element plus will be better, waiting for the author's reply

This migration will not be very difficult. I believe that as long as communication is timely, it will be completed soon.

We are from China. I don't know whether the author has Telegram, because it is prohibited in our country, but I can use vpn

**Comment by sww1740747758** [comment]
> iview



> > > There is time difference between us, and communication may not be timely.
> > 
> > 
> > Yes, I think element-plus will work well, I didn't know about it yet.
> > Exactly, I'm from Brazil, and I can only move at night, after leaving work, so there will always be this delay in the response, but I believe that this upgrade will be quick, among other adjustments that we can make together.
> > I don't know if the project has a Telegram channel, if so, we can discuss the project there.
> 
> Thank you both for your discussion, I think about it this way： 1、The UI looks a little more polished,I prefer iview's Message style. 2、The UI component satisfies the scenario of our editor interface, iview-plus and element-plus all can be。 3、The main focus is on improving the functionality of the editor，Don't expect to stretch out too long on the UI framework。
> 
> I haven't used element-plus, Will it be better than iview ? My English is poor, It often has to be edited into Chinese and then published with translation software, Important discussions are more likely to use issues or discussions,Whether it is necessary to build a web version of the live chat room?
> 
> 感谢两位的讨论，我是这样想的： 1、UI看起来更精致，我更喜欢iview的 Message 样式。 2、UI组件可以满足编辑器的场景，iview-plus 和 element-plus都满足。 3、希望把精力集中在编辑器的功能上，不要在框架上卡太长时间。
> 
> 我没用过element-plus，是比iview有更多的优势吗？我英文不是特别好，经常需要把文字编辑好用翻译软件再转成英文，更重要的讨论希望在issue或者discussions中保留下来，如果特别必要，是不是可以开一个实时聊天的web论坛，我忘记叫什么名字了，S开头的一个论坛工具，用的也比较多。

Because element plus may be more popular, some international friends may not know about iview, and using the more popular UI will attract more like-minded people. I hope that after the project is relocated, someone can directly use it in the project. Now, the basic standard configuration of vue3 is element plus, so it is recommended to use it.

因为element plus 可能更加热门一些 国际友人可能不知道iview，使用更加热门的UI 会吸引更过志同道合的人，我希望这个项目重新迁移后，可以有人直接在项目使用，现在使用vue3基本标配就是element plus ，所以建议使用。

**Comment by sww1740747758** [comment]
> > > There is time difference between us, and communication may not be timely.
> > 
> > 
> > Yes, I think element-plus will work well, I didn't know about it yet.
> > Exactly, I'm from Brazil, and I can only move at night, after leaving work, so there will always be this delay in the response, but I believe that this upgrade will be quick, among other adjustments that we can make together.
> > I don't know if the project has a Telegram channel, if so, we can discuss the project there.
> 
> Thank you both for your discussion, I think about it this way： 1、The UI looks a little more polished,I prefer iview's Message style. 2、The UI component satisfies the scenario of our editor interface, iview-plus and element-plus all can be。 3、The main focus is on improving the functionality of the editor，Don't expect to stretch out too long on the UI framework。
> 
> I haven't used element-plus, Will it be better than iview ? My English is poor, It often has to be edited into Chinese and then published with translation software, Important discussions are more likely to use issues or discussions,Whether it is necessary to build a web version of the live chat room?
> 
> 感谢两位的讨论，我是这样想的： 1、UI看起来更精致，我更喜欢iview的 Message 样式。 2、UI组件可以满足编辑器的场景，iview-plus 和 element-plus都满足。 3、希望把精力集中在编辑器的功能上，不要在框架上卡太长时间。
> 
> 我没用过element-plus，是比iview有更多的优势吗？我英文不是特别好，经常需要把文字编辑好用翻译软件再转成英文，更重要的讨论希望在issue或者discussions中保留下来，如果特别必要，是不是可以开一个实时聊天的web论坛，我忘记叫什么名字了，S开头的一个论坛工具，用的也比较多。

如果你有Telegram 我们可以在上面联系

**Comment by nihaojob** [comment]
> > iview
> 
> > > > There is time difference between us, and communication may not be timely.
> > > 
> > > 
> > > Yes, I think element-plus will work well, I didn't know about it yet.
> > > Exactly, I'm from Brazil, and I can only move at night, after leaving work, so there will always be this delay in the response, but I believe that this upgrade will be quick, among other adjustments that we can make together.
> > > I don't know if the project has a Telegram channel, if so, we can discuss the project there.
> > 
> > 
> > Thank you both for your discussion, I think about it this way： 1、The UI looks a little more polished,I prefer iview's Message style. 2、The UI component satisfies the scenario of our editor interface, iview-plus and element-plus all can be。 3、The main focus is on improving the functionality of the editor，Don't expect to stretch out too long on the UI framework。
> > I haven't used element-plus, Will it be better than iview ? My English is poor, It often has to be edited into Chinese and then published with translation software, Important discussions are more likely to use issues or discussions,Whether it is necessary to build a web version of the live chat room?
> > 感谢两位的讨论，我是这样想的： 1、UI看起来更精致，我更喜欢iview的 Message 样式。 2、UI组件可以满足编辑器的场景，iview-plus 和 element-plus都满足。 3、希望把精力集中在编辑器的功能上，不要在框架上卡太长时间。
> > 我没用过element-plus，是比iview有更多的优势吗？我英文不是特别好，经常需要把文字编辑好用翻译软件再转成英文，更重要的讨论希望在issue或者discussions中保留下来，如果特别必要，是不是可以开一个实时聊天的web论坛，我忘记叫什么名字了，S开头的一个论坛工具，用的也比较多。
> 
> Because element plus may be more popular, some international friends may not know about iview, and using the more popular UI will attract more like-minded people. I hope that after the project is relocated, someone can directly use it in the project. Now, the basic standard configuration of vue3 is element plus, so it is recommended to use it.
> 
> 因为element plus 可能更加热门一些 国际友人可能不知道iview，使用更加热门的UI 会吸引更过志同道合的人，我希望这个项目重新迁移后，可以有人直接在项目使用，现在使用vue3基本标配就是element plus ，所以建议使用。

Your advice is particularly good，I think it's possible to separate the vue2 upgrade from the UI framework replacement，We can do this in two separate tasks，The first one upgrades the scaffolding and vue to Vue3，UI using the existing framework, the cost of renovation will be relatively small；The second step is to replace the UI frame,Before we replace it, we can discuss whether element or another framework is a better fit,The current priority is still Vue and scaffolding version upgrade, what do you think?


你的建议特别好，我觉得可以把升级vue2和替换UI框架分开来，我们可以分2个任务来完成，第一步先把脚手架和vue升级为Vue3，UI沿用现有框架，改造成本也会相对较小；第二步再替换UI框架，替换前我们可以再讨论下是使用element还是其他框架更好合适。当前优先级比较高的还是Vue和脚手架版本升级，两位觉得呢？

**Comment by asang28** [comment]
> > > iview
> > 
> > 
> > > > > There is time difference between us, and communication may not be timely.
> > > > 
> > > > 
> > > > Yes, I think element-plus will work well, I didn't know about it yet.
> > > > Exactly, I'm from Brazil, and I can only move at night, after leaving work, so there will always be this delay in the response, but I believe that this upgrade will be quick, among other adjustments that we can make together.
> > > > I don't know if the project has a Telegram channel, if so, we can discuss the project there.
> > > 
> > > 
> > > Thank you both for your discussion, I think about it this way： 1、The UI looks a little more polished,I prefer iview's Message style. 2、The UI component satisfies the scenario of our editor interface, iview-plus and element-plus all can be。 3、The main focus is on improving the functionality of the editor，Don't expect to stretch out too long on the UI framework。
> > > I haven't used element-plus, Will it be better than iview ? My English is poor, It often has to be edited into Chinese and then published with translation software, Important discussions are more likely to use issues or discussions,Whether it is necessary to build a web version of the live chat room?
> > > 感谢两位的讨论，我是这样想的： 1、UI看起来更精致，我更喜欢iview的 Message 样式。 2、UI组件可以满足编辑器的场景，iview-plus 和 element-plus都满足。 3、希望把精力集中在编辑器的功能上，不要在框架上卡太长时间。
> > > 我没用过element-plus，是比iview有更多的优势吗？我英文不是特别好，经常需要把文字编辑好用翻译软件再转成英文，更重要的讨论希望在issue或者discussions中保留下来，如果特别必要，是不是可以开一个实时聊天的web论坛，我忘记叫什么名字了，S开头的一个论坛工具，用的也比较多。
> > 
> > 
> > Because element plus may be more popular, some international friends may not know about iview, and using the more popular UI will attract more like-minded people. I hope that after the project is relocated, someone can directly use it in the project. Now, the basic standard configuration of vue3 is element plus, so it is recommended to use it.
> > 因为element plus 可能更加热门一些 国际友人可能不知道iview，使用更加热门的UI 会吸引更过志同道合的人，我希望这个项目重新迁移后，可以有人直接在项目使用，现在使用vue3基本标配就是element plus ，所以建议使用。
> 
> Your advice is particularly good，I think it's possible to separate the vue2 upgrade from the UI framework replacement，We can do this in two separate tasks，The first one upgrades the scaffolding and vue to Vue3，UI using the existing framework, the cost of renovation will be relatively small；The second step is to replace the UI frame,Before we replace it, we can discuss whether element or another framework is a better fit,The current priority is still Vue and scaffolding version upgrade, what do you think?
> 
> 你的建议特别好，我觉得可以把升级vue2和替换UI框架分开来，我们可以分2个任务来完成，第一步先把脚手架和vue升级为Vue3，UI沿用现有框架，改造成本也会相对较小；第二步再替换UI框架，替换前我们可以再讨论下是使用element还是其他框架更好合适。当前优先级比较高的还是Vue和脚手架版本升级，两位觉得呢？

It seems that view design is not friendly enough for vue3, and the official website code is also written in the same way as vue2. I suggest upgrading all at once. Don't do nothing. It's up to you to decide. I suggest upgrading scaffolding and element plus directly

好像view-design 对于vue3的支持不够友好，官网的代码也是vue2 的写法。我建议一步到位，要升级都升级，不要做无用功，最后看你们决定吧，我建议直接升级脚手架和element plus

**Comment by nihaojob** [comment]
@asang28 刚才看了下View UI Plus，View 对Vue3 来说确实还有很多问题，我赞同直接升级到element plus，不过不确定工作量会增加多少，@icleitoncosta  你怎么看？是否需要我们一起升级？

@asang28  I just looked at View UI Plus，View does have a lot of problems with Vue3，I'm in favor of upgrading directly to element plus, But it's not sure how much more work will be  @done, @icleitoncosta  What do you think? Do we need to upgrade together?

**Comment by icleitoncosta** [comment]
It will increase the work a little, but I believe it is even simple. The most annoying part will be the alignment and divs that maybe should change from one to the other, but I believe it's not something that big because the frameworks follow a pattern too, I'll start migrating to element-plus and let's talk.

**Comment by nihaojob** [comment]
> It will increase the work a little, but I believe it is even simple. The most annoying part will be the alignment and divs that maybe should change from one to the other, but I believe it's not something that big because the frameworks follow a pattern too, I'll start migrating to element-plus and let's talk.

Thank you for your hard work, If the adjustment is more tedious,You can start with iview plus or have a more suitable Vue3 UI framework,It's an iteration that wants to be able to run in small steps, Lest you be too tired, Feel free to let me know if you need me.

辛苦你了，如果调整比较繁琐，可以先用iview plus或者有更适合的Vue3 UI框架都可以，还是希望能够小步快跑的迭代，怕你太累，如果需要我的话随时沟通。

**Comment by icleitoncosta** [comment]
I started the migration to Vue3.
This week I had to do a lot of chores, so I didn't have time to move beforehand.

I decided to opt for "view-ui-plus", since the project is all based on the previous version, and the migration would be easier.

The migration still needs some design and translation tweaks, but I have a bigger problem and would like your help.

In FabricJS's Canva build, it just doesn't show up.
The import buttons work and even when I click on save the image, it downloads the template that was chosen correctly, however, the canvas box simply does not exist.

Can anyone help me with this step?
I don't understand or know FabricJS in depth.

Here's the branch:
https://github.com/icleitoncosta/vue-fabric-editor/tree/migrate-vue3

**Comment by icleitoncosta** [comment]
> I started the migration to Vue3. This week I had to do a lot of chores, so I didn't have time to move beforehand.
> 
> I decided to opt for "view-ui-plus", since the project is all based on the previous version, and the migration would be easier.
> 
> The migration still needs some design and translation tweaks, but I have a bigger problem and would like your help.
> 
> In FabricJS's Canva build, it just doesn't show up. The import buttons work and even when I click on save the image, it downloads the template that was chosen correctly, however, the canvas box simply does not exist.
> 
> Can anyone help me with this step? I don't understand or know FabricJS in depth.
> 
> Here's the branch: https://github.com/icleitoncosta/vue-fabric-editor/tree/migrate-vue3

The error is caused because in version 3 the provides are declared before creation, so it cannot find the #canvas in the html.

An alternative I thought would be to use props, instead of inject, but as it may be a limitation of my knowledge, I would like your suggestion.

Greetings

**Comment by nihaojob** [comment]
> > I started the migration to Vue3. This week I had to do a lot of chores, so I didn't have time to move beforehand.
> > 
> > I decided to opt for "view-ui-plus", since the project is all based on the previous version, and the migration would be easier.
> > 
> > The migration still needs some design and translation tweaks, but I have a bigger problem and would like your help.
> > 
> > In FabricJS's Canva build, it just doesn't show up. The import buttons work and even when I click on save the image, it downloads the template that was chosen correctly, however, the canvas box simply does not exist.
> > 
> > Can anyone help me with this step? I don't understand or know FabricJS in depth.
> > 
> > Here's the branch: https://github.com/icleitoncosta/vue-fabric-editor/tree/migrate-vue3
> 
> The error is caused because in version 3 the provides are declared before creation, so it cannot find the #canvas in the html.
> 
> An alternative I thought would be to use props, instead of inject, but as it may be a limitation of my knowledge, I would like your suggestion.
> 
> Greetings

Copy that. I'll try to fix it

**Comment by nihaojob** [comment]
@icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。

@icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.

**Comment by icleitoncosta** [comment]
> @icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。
> 
> 
> 
> @icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.

But if we put in "mounted" the "provides" will be passed before initialization, in components like setSize it will give errors, as it has not yet been instantiated in mounted, since inject is called in create.

did you manage to make it work without errors there?

I could only make it work without errors using props.

**Comment by nihaojob** [comment]
> > @icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。
> > @icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.
> 
> But if we put in "mounted" the "provides" will be passed before initialization, in components like setSize it will give errors, as it has not yet been instantiated in mounted, since inject is called in create.
> 
> did you manage to make it work without errors there?
> 
> I could only make it work without errors using props.

The parent of the set-size component is controlled by v-if="show". The show property is initialized to true.

**Comment by nihaojob** [comment]
@icleitoncosta HI, I created a branch [perf-vue3](https://github.com/nihaojob/vue-fabric-editor/tree/perf-vue3), Another friend is also interested in the Vue3 upgrade and we can discuss it together, @QJune 。

**Comment by QJune** [comment]
> > @icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。
> > @icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.
> 
> But if we put in "mounted" the "provides" will be passed before initialization, in components like setSize it will give errors, as it has not yet been instantiated in mounted, since inject is called in create.
> 
> did you manage to make it work without errors there?
> 
> I could only make it work without errors using props.


> > @icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。
> > @icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.
> 
> But if we put in "mounted" the "provides" will be passed before initialization, in components like setSize it will give errors, as it has not yet been instantiated in mounted, since inject is called in create.
> 
> did you manage to make it work without errors there?
> 
> I could only make it work without errors using props.

We don't have to use "provides", we can use Publish subscriber pattern or vuex.Do  you migrated it on the branch of perf-vue3?let me try to solve this problem

**Comment by QJune** [comment]
> I can help with that migration. From what I understand they want to carry out the entire project migration to Vue3, right?

hi, do you migrate it with vue3+ts？

**Comment by icleitoncosta** [comment]
> hi, do you migrate it with vue3+ts？

Yesterday I couldn't continue the migration, I arrived very late from work.

I believe that using "vuex" would put one more library without much need, because vuex must be discontinued in favor of Pinia, and we can do without it.

I didn't migrate to TS, but we can do it that way if you prefer.

**Comment by QJune** [comment]
> I'll be free next week.You can create a branch or a repository.we can do it together.

**Comment by QJune** [comment]
> > hi, do you migrate it with vue3+ts？
> 
> Yesterday I couldn't continue the migration, I arrived very late from work.
> 
> I believe that using "vuex" would put one more library without much need, because vuex must be discontinued in favor of Pinia, and we can do without it.
> 
> I didn't migrate to TS, but we can do it that way if you prefer.

> I'll be free next week.You can create a branch or a repository.we can do it together.

**Comment by QJune** [comment]
> > hi, do you migrate it with vue3+ts？
> 
> Yesterday I couldn't continue the migration, I arrived very late from work.
> 
> I believe that using "vuex" would put one more library without much need, because vuex must be discontinued in favor of Pinia, and we can do without it.
> 
> I didn't migrate to TS, but we can do it that way if you prefer.

>> I'll be free next week.You can create a branch or a repository.we can do it together.

**Comment by QJune** [comment]
> > > hi, do you migrate it with vue3+ts？
> > 
> > 
> > Yesterday I couldn't continue the migration, I arrived very late from work.
> > I believe that using "vuex" would put one more library without much need, because vuex must be discontinued in favor of Pinia, and we can do without it.
> > I didn't migrate to TS, but we can do it that way if you prefer.
>

> > > yes, It's just Pinia. 
> > > I'll be free next week.You can create a branch or a repository.we can do it together.
> > > i want to use ts.because i want to learn ts.

**Comment by nihaojob** [comment]
> > hi, do you migrate it with vue3+ts？
> 
> Yesterday I couldn't continue the migration, I arrived very late from work.
> 
> I believe that using "vuex" would put one more library without much need, because vuex must be discontinued in favor of Pinia, and we can do without it.
> 
> I didn't migrate to TS, but we can do it that way if you prefer.

Thanks for your hard work, Take care of yourself, Not in a particular hurry, Just go at your pace, Maybe you can submit the code first,We do it together。

辛苦你了，照顾好自己，这件事情不着急，按你的节奏慢慢来就好，或者你也可以先提交代码，我们一起做。

**Comment by QJune** [comment]
> > > > @icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。
> > > > @icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.
> > > 
> > > 
> > > But if we put in "mounted" the "provides" will be passed before initialization, in components like setSize it will give errors, as it has not yet been instantiated in mounted, since inject is called in create.
> > > did you manage to make it work without errors there?
> > > I could only make it work without errors using props.
> > 
> > 
> > > > @icleitoncosta   将初始化代码从 setup 迁移到 mounted 就可以了，在你的分支上我本地已经运行正常了，因为fabric初始化元素需要确保DOM元素渲染完成。
> > > > @icleitoncosta   Just migrate the initialization code from setup to mounted,I'm already running fine locally on your branch, because fabric initializing elements requires making sure the DOM elements are rendered.
> > > 
> > > 
> > > But if we put in "mounted" the "provides" will be passed before initialization, in components like setSize it will give errors, as it has not yet been instantiated in mounted, since inject is called in create.
> > > did you manage to make it work without errors there?
> > > I could only make it work without errors using props.
> > 
> > 
> > We don't have to use "provides", we can use Publish subscriber pattern or vuex.Do you migrated it on the branch of perf-vue3?let me try to solve this problem
> 
> First of all thanks to [QJune](https://github.com/QJune) for the idea,I have the same idea as [icleitoncosta](https://github.com/icleitoncosta),Introducing unnecessary dependencies can lead to a larger work load,So far it looks like we can do this without using state management and still work cleanly;About TS,We want the same thing,Make the project and the contributors better。
> 
> 首先感谢[QJune](https://github.com/QJune)的想法，我和[icleitoncosta](https://github.com/icleitoncosta)的想法一样，引入不必要的依赖可能会让工作量变大，目前看我们可以在不使用状态管理下简洁的工作，关于TS，我们目标是一致的，让项目和贡献者都变得更好。

we can do it with events. The library had uesd in master

**Comment by asang28** [comment]
我已经完成了迁移到vue3

看到你们使用了iview,所以我就着手自己迁移了

我使用了 element plus vite脚手架

不知道功能迁移的完不完整

还请各位如果有兴趣和时间一起帮我看看

分支地址是:
https://github.com/asang28/vue3-fabric-edito.git

I have completed the migration to vue3

I saw that you used iview, so I started to migrate myself

I used the element plus vite scaffold

I don't know whether the function migration is complete

Please also help me if you are interested and time

Here's the branch:
https://github.com/asang28/vue3-fabric-edito.git

**Comment by nihaojob** [comment]
> https://github.com/asang28/vue3-fabric-editor.git

Executive force is too strong, it was really cool。

执行力太强了，真酷。

**Comment by asang28** [comment]
> > https://github.com/asang28/vue3-fabric-editor.git
> 
> Executive force is too strong, it was really cool。
> 
> 执行力太强了，真酷。


It's not perfect in our spare time. Let's put forward suggestions together

闲暇时间弄的，不够完善的地方大家一起提提意见

**Comment by vockalimo** [comment]
vue3 ,   .. https://github.com/vockalimo/vue-fabric-editor
hmm .  maybe can help ~
