### ISSUE TITLE
新增pull request模板 

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#163]
https://zhuanlan.zhihu.com/p/467670042
github fork的代码如何保持与原来代码同步

增加提示，要求合并前先同步代码

**Comment by Qiu-Jun** [comment]
> https://zhuanlan.zhihu.com/p/467670042 github fork的代码如何保持与原来代码同步
> 
> 增加提示，要求合并前先同步代码

方法一好像会有一个自动合并的commit

**Comment by nihaojob** [comment]
我后边把步骤建一个模板，减少一下误操作

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/ae1c42575246cfddb2ec8ff499cd8c12e87c6cb7
