### ISSUE TITLE
修改画布尺寸改为弹框形式，并增加二次确认

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#169]
为什么：
直接修改尺寸并不是一个体验特别好的事情，在没有提示的情况下直接把画布尺寸修改了，这是一个重要的行为，需要增加一个二次确认。

交互说明：
1. 默认展示宽高尺寸，不可直接修改，提供修改按钮。
2. 点击按钮后弹出尺寸修改弹框，可进行尺寸修改。
3. 点击确定时弹出二次确认，确定后修改尺寸。

效果参考：
![20230415120032_rec_](https://user-images.githubusercontent.com/13534626/232181904-ff711980-c7c6-42ac-8385-7dc378338291.gif)

**Comment by a847244052** [comment]
这个还做吗 是不是需要更新下需求

**Comment by Qiu-Jun** [comment]
> 这个还做吗 是不是需要更新下需求

这个目前还没完成，修改尺寸的方式我记得是有两种，一种是input，另一种是点击。你可以在setSize组件那里，onChange回调和click事件添加弹窗确实就好
