### ISSUE TITLE
Questions for migrations

### ISSUE THREAD

**Issue by icleitoncosta** [nihaojob/vue-fabric-editor#18]
Hello, I started the migration to Vue3, however, right away, I already had a problem.
The view-design library doesn't support vue3, only vue1 or vue2, do you have any suggestions of what we can use to replace it?

**Comment by nihaojob** [comment]
Just looking at this issue, you can use iview-plus, which supports vue3. With iview-plus, we hardly need to change the logic of the component.


刚刚看到这个issue，可以使用iview-plus，支持vue3，使用iview-plus我们几乎不用修改组件的逻辑。
