### ISSUE TITLE
无法编辑 1920 X 1080 背景图片，背景无法设置png透明

### ISSUE THREAD

**Issue by anime777** [nihaojob/vue-fabric-editor#2]
1. 无法编辑 1920 X 1080 背景图片，
2. 背景无法设置png透明

**Comment by nihaojob** [comment]
收到，我后期验证修复下，也欢迎提PR，一起维护。

**Comment by nihaojob** [comment]
> 收到，我后期验证修复下，也欢迎提PR，一起维护。



> 1. 无法编辑 1920 X 1080 背景图片，
> 2. 背景无法设置png透明


收到，我后期验证修复下，也欢迎提PR，一起维护。

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/45
