### ISSUE TITLE
图片裁切功能

### ISSUE THREAD

**Issue by duriann** [nihaojob/vue-fabric-editor#214]
希望能加上类似这网站的图片裁切功能https://www.shutterstock.com/zh/editor/image/elderly-man-walking-cane-hand-behind-2068574411

**Comment by nihaojob** [comment]
> 希望能加上类似这网站的图片裁切功能https://www.shutterstock.com/zh/editor/image/elderly-man-walking-cane-hand-behind-2068574411

是有规划增加的，可以看下Demo，https://code.juejin.cn/pen/7140874112771031075

**Comment by gentlemanZhang** [comment]
@nihaojob  demo地址好像失效了，提示“”代码不存在“

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/405
