### ISSUE TITLE
字体素材迁移到七牛云

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#222]

**Comment by nihaojob** [comment]
@caorufu 是可用的，迁移到七牛云的初衷只是为了让国内访问更快，因为很多本地环境或者网络的原因没办法访问到githu，所有偶尔会出现字体拉取不成功的问题。

**Comment by caorufu** [comment]
> @caorufu 是可用的，迁移到七牛云的初衷只是为了让国内访问更快，因为很多本地环境或者网络的原因没办法访问到githu，所有偶尔会出现字体拉取不成功的问题。

嗯嗯，感谢大佬反馈~我也提供一个粗暴的解决方法：把free-font那个项目clone到磁盘上，再挂个文件服务器，下载请求就不必往外转了，方便快捷。字体项目大概1个G

**Comment by nihaojob** [comment]
@caorufu 确实可以通过这个方式解决，不过并不是太友好，还是想迁移到一个开放稳定的空间里。

**Comment by nihaojob** [comment]
https://github.com/typekit/webfontloader

**Comment by linrb685** [comment]
> 目前的字体下载部分是已经无法使用了吗？我看/fontFile配置的代理都拿不到数据了。请求结果：
> 
> > 网址请求: [http://localhost:3000/fontFile/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97 %A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97% A8%E6%AD%A3%E9%81%93%E7%B2%97%E4%B9%A6%E4%BD%93.ttf请求方法: GET状态](http://localhost:3000/fontFile/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E5%BA%9E%E9%97%A8%E6%AD%A3%E9%81%93%E7%B2%97%E4%B9%A6%E4%BD%93.ttf)
> > 代码
> > : 500 Internal Server Error
> > 远程地址: [:: 1]:3000
> > 引荐来源网址政策：跨域时严格源
> 
> 想要按目前的配置解析出来的目录是：
> 
> > https://github.com/wordshub/free-font/raw/master/assets/font/
> 
> 但是他那个项目最新的目录结构引用部分为：
> 
> > https://github.com/wordshub/free-font/blob/master/assets/font/
> > 完整示例：
> > [https://github.com/wordshub/free-font/blob/master/assets/font/%E4% B8%AD%E6%96%87/%E6%80%9D%E6%BA%90%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6% 80%9D%E6%BA%90%E5%AE%8B%E4%BD%93/SourceHanSerifCN-Bold.ttf](https://github.com/wordshub/free-font/blob/master/assets/font/%E4%B8%AD%E6%96%87/%E6%80%9D%E6%BA%90%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%80%9D%E6%BA%90%E5%AE%8B%E4%BD%93/SourceHanSerifCN-Bold.ttf)
> 
> 需要将路由里的“原始”改成“blob”工件吗？

大佬，我在使用字体的时候也是遇到这个问题，明明在vite.config.ts已经配置了以fontFile开头的请求会被替换成github.com。但是点击未下载的字体，他访问的却还是localhost？这个怎么解决
