### ISSUE TITLE
Is it possible to use AI painting algorithm to automatically generate posters？

### ISSUE THREAD

**Issue by seawater668** [nihaojob/vue-fabric-editor#223]

**Comment by nihaojob** [comment]
This is a front-end project, no back-end services or AI capabilities, so if you're building an AI photo app, maybe the editor features will help you with photo editing.

这只是一个前端项目，并没有后端服务和AI能力，如果你正在构建AI图片应用，或许编辑器的功能能够帮助你进行图片编辑。
