### ISSUE TITLE
PSD导入功能

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#231]
参考 https://github.com/LvHuaiSheng/vue-fabric-editor-element 项目实现

**Comment by Qiu-Jun** [comment]
psdjs局限太大，复杂一点的都解析不出，只能解析简单的图层信息

**Comment by nihaojob** [comment]
> psdjs局限太大，复杂一点的都解析不出，只能解析简单的图层信息

迅排使用了这个工具 https://webtoon.github.io/psd/，并且元素转换成了base64，我们是不是也可以按照这思路来开发？

**Comment by Qiu-Jun** [comment]
> > psdjs局限太大，复杂一点的都解析不出，只能解析简单的图层信息
> 
> 
> 
> 迅排使用了这个工具 https://webtoon.github.io/psd/，并且元素转换成了base64，我们是不是也可以按照这思路来开发？

有空试试

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/099c7c6afdb66a963b847135d003e63cc8dfb371

**Comment by jerry-f** [comment]
目前开源版本的psd解析确实有很多局限， 好多解析都有问题。 不够商业版本解析好像要好很多。

**Comment by nihaojob** [comment]
> 目前开源版本的psd解析确实有很多局限， 好多解析都有问题。 不够商业版本解析好像要好很多。

是呢 商业版在各个方面更精细一些，我们投入的时间和成本也多一些
