### ISSUE TITLE
默认的两个字体似乎不生效

### ISSUE THREAD

**Issue by fuxiaoye** [nihaojob/vue-fabric-editor#233]
“汉体”和“华康金刚黑”用于文字上后文字并无变化，导出json显示FontFamily均为"arial"

**Comment by nihaojob** [comment]
> “汉体”和“华康金刚黑”用于文字上后文字并无变化，导出json显示FontFamily均为"arial"

谢谢你的反馈，确实不生效了，可能是在迭代过程中，出现了问题，如果感兴趣，欢迎PR这个bug。

**Comment by Qiu-Jun** [comment]
> > “汉体”和“华康金刚黑”用于文字上后文字并无变化，导出json显示FontFamily均为"arial"
> 
> 谢谢你的反馈，确实不生效了，可能是在迭代过程中，出现了问题，如果感兴趣，欢迎PR这个bug。

我试了试最新的代码，没问题。可能是你们没开梯子。导致加载失败了

**Comment by fuxiaoye** [comment]
> > > “汉体”和“华康金刚黑”用于文字上后文字并无变化，导出json显示FontFamily均为"arial"
> > 
> > 
> > 谢谢你的反馈，确实不生效了，可能是在迭代过程中，出现了问题，如果感兴趣，欢迎PR这个bug。
> 
> 我试了试最新的代码，没问题。可能是你们没开梯子。导致加载失败了

之前问题的确存在，试了一下最新的代码，问题已修复。
