### ISSUE TITLE
请问后续有支持动效的想法吗

### ISSUE THREAD

**Issue by langren1353** [nihaojob/vue-fabric-editor#234]
请问后续是否考虑增加对图片或者某些独立组件的动效添加
比如说预览的时候增加抖动、划入、划出等动效呢

**Comment by nihaojob** [comment]
> 请问后续是否考虑增加对图片或者某些独立组件的动效添加 比如说预览的时候增加抖动、划入、划出等动效呢

我不太确定你的应用场景是什么，目前的项目只是一个图片编辑器，加上动画以后，是为了支持导出git吗
