### ISSUE TITLE
[bug] 锁定一个可被锁定的元素后，将鼠标选中其他元素，无法再选中被锁定的图层，进而导致无法解锁。

### ISSUE THREAD

**Issue by kido050313** [nihaojob/vue-fabric-editor#236]
解决方法：只设置hascontrol 属性，不设置selectable属性
![image](https://github.com/nihaojob/vue-fabric-editor/assets/29145782/dce473f2-24a1-4f7b-8914-13c734fcd19a)

**Comment by nihaojob** [comment]
@kido050313 可以从左侧 图层面板中选中，然后再点击解锁即可。
