### ISSUE TITLE
撤销重做

### ISSUE THREAD

**Issue by xiaozeo** [nihaojob/vue-fabric-editor#24]
大佬，为什么点击图层会记入一次撤销呢？能否优化一下 && 是否可以恢复删除的呢？

**Comment by nihaojob** [comment]
> 大佬，为什么点击图层会记入一次撤销呢？能否优化一下 && 是否可以恢复删除的呢？

大佬好，现在历史记录模块是个很粗糙的实现，把所有事件都记录了下拉，但是可以实现针对特定事件的过滤，如果有你感兴趣或者比较着急的话可以提交一个PR，改动起来很简单，在save方法中，在push前加一下过滤。

https://github.com/nihaojob/vue-fabric-editor/blob/92871b7f0a37963abb7151607c011fb398e8d3bb/src/components/history.vue#L33-L42

https://github.com/nihaojob/vue-fabric-editor/blob/92871b7f0a37963abb7151607c011fb398e8d3bb/src/components/history.vue#L46-L52

**Comment by xiaozeo** [comment]
我代码还没整理好，先不提交PR啦，周末尝试了一下，还是没搞出来。。。

**Comment by nihaojob** [comment]
> 我代码还没整理好，先不提交PR啦，周末尝试了一下，还是没搞出来。。。

可以加我微信哈，13146890191，有一个讨论群可以交流。

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/9df26a5fa46818fae2df170e2d1789552230b9df
