### ISSUE TITLE
颜色渐变：实际点击位置与定位不符

### ISSUE THREAD

**Issue by linen1794** [nihaojob/vue-fabric-editor#240]
<img width="344" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/30710337/eec1b6b6-ec23-4812-b4f3-35540038a352">

**Comment by Qiu-Jun** [comment]
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/30710337/248731754-eec1b6b6-ec23-4812-b4f3-35540038a352.png">

你好，这个问题不单独解决了。 [渐变组件正则升级，到时候会一起解决](https://github.com/Qiu-Jun/color-gradient-picker-vue3/issues/4)

**Comment by Qiu-Jun** [comment]
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/30710337/248731754-eec1b6b6-ec23-4812-b4f3-35540038a352.png">

这边问题暂时解决了，但没有从根源处理，后面升级组件会处理这个问题
