### ISSUE TITLE
导出为json时中文乱码

### ISSUE THREAD

**Issue by fuxiaoye** [nihaojob/vue-fabric-editor#243]
导出为json时textbox类型的text和fontFamily中的中文会乱码，导致生成的json无法再次导入进行编辑。

**Comment by Qiu-Jun** [comment]
> 导出为json时textbox类型的text和fontFamily中的中文会乱码，导致生成的json无法再次导入进行编辑。

暂时恢复了旧的下载方法，downloadjs对中文处理确实是有问题

**Comment by nihaojob** [comment]
已回退功能。
