### ISSUE TITLE
元素旋转角度后, 对齐方法计算的位置有误

### ISSUE THREAD

**Issue by rolitter** [nihaojob/vue-fabric-editor#245]
同样是左对齐
未旋转
![image](https://github.com/nihaojob/vue-fabric-editor/assets/27326998/0d41ec83-c772-4232-8852-3351ea182b4f)
旋转了角度
![image](https://github.com/nihaojob/vue-fabric-editor/assets/27326998/54916c58-4ed8-4db7-953b-e1f1c152d7dd)

**Comment by nihaojob** [comment]
@rolitter 感谢你的反馈，确实是个bug，如果你感兴趣的话，欢迎PR解决这个问题。

**Comment by rolitter** [comment]
已提交pr
@nihaojob

**Comment by nihaojob** [comment]
@rolitter 感谢提交PR，我周末测试后合并下。

**Comment by nihaojob** [comment]
> > @rolitter 感谢提交PR，我周末测试后合并下。
> 
> 大佬最近有点卷，持续一段时间了，哈哈

June能帮忙看下吗？老家有点事情在处理😂

**Comment by Qiu-Jun** [comment]
> > > @rolitter 感谢提交PR，我周末测试后合并下。
> > 
> > 大佬最近有点卷，持续一段时间了，哈哈
> 
> June能帮忙看下吗？老家有点事情在处理😂

好

**Comment by Qiu-Jun** [comment]
> 已提交pr @nihaojob #246

已合并
