### ISSUE TITLE
喜欢这个项目，要是有react版本就好了

### ISSUE THREAD

**Issue by A-ANing** [nihaojob/vue-fabric-editor#250]

**Comment by nihaojob** [comment]
@A-ANing 我们刚进行了插件化重构，后边等Editor Core 和 插件稳定以后可能会开发react版本，大佬感兴趣的话 可以一起参与进来哈。

**Comment by Qiu-Jun** [comment]
> 

有想法，没时间😂

**Comment by w602542704** [comment]
> 

这个项目封装很颗粒化，挺好的，想问你们这是业余爱好参与的项目，还是公司在做的项目呀

**Comment by 1123612483** [comment]
> @A-ANing 我们刚进行了插件化重构，后边等Editor Core 和 插件稳定以后可能会开发react版本，大佬感兴趣的话 可以一起参与进来哈。

react版本我想参与一下

**Comment by x007xyz** [comment]
用React做了初步实现，可以看下https://github.com/x007xyz/r-fabric-editor

**Comment by nihaojob** [comment]
太酷辣  赞 👍
