### ISSUE TITLE
useSelect是不能做状态容器么

### ISSUE THREAD

**Issue by lichenglong-blog** [nihaojob/vue-fabric-editor#254]
我尝试做个drag的插槽组件，因为有很多元素都用drag，所以兼听drag事件得提升到全局不然就重复了，同时drag的xy坐标我要存起来，在useSelect存xy坐标，发现在画出来的时候xy坐标没有打出来，似乎hooks文件夹下的useSelect不能作为状态容器，因为每次引入useSelect（）都要重新创建新的状态，请教下是不是这不能作为全局状态容器呢？那他的作用是不是只能局部用？。
![image](https://github.com/nihaojob/vue-fabric-editor/assets/24689873/444e2591-e245-474d-842c-1fbbedb38ff1)
![image](https://github.com/nihaojob/vue-fabric-editor/assets/24689873/dcd4e998-3ad7-4112-b4b7-b6ee17043e52)

**Comment by w602542704** [comment]
大佬 @liumingye

**Comment by Qiu-Jun** [comment]
这个useSelected是项目vue2 mixins的替代方案……

**Comment by Qiu-Jun** [comment]
> 我尝试做个drag的插槽组件，因为有很多元素都用drag，所以兼听drag事件得提升到全局不然就重复了，同时drag的xy坐标我要存起来，在useSelect存xy坐标，发现在画出来的时候xy坐标没有打出来，似乎hooks文件夹下的useSelect不能作为状态容器，因为每次引入useSelect（）都要重新创建新的状态，请教下是不是这不能作为全局状态容器呢？那他的作用是不是只能局部用？。
> 
> ![image](https://github.com/nihaojob/vue-fabric-editor/assets/24689873/444e2591-e245-474d-842c-1fbbedb38ff1)
> 
> ![image](https://github.com/nihaojob/vue-fabric-editor/assets/24689873/dcd4e998-3ad7-4112-b4b7-b6ee17043e52)
> 
> 
> 
> 

关于hooks的使用，你套个函数就行了
