### ISSUE TITLE
画笔功能

### ISSUE THREAD

**Issue by gentlemanZhang** [nihaojob/vue-fabric-editor#266]
1.自定义画笔粗细
2.自定义画笔颜色

**Comment by zJunyu** [comment]
这样就可以涂鸦了

**Comment by nihaojob** [comment]
![image](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/38e5c67d-cfd0-4967-b838-3e31db3aa0cd)
已支持基础画笔，其他功能大佬们可根据代码进行调整
