### ISSUE TITLE
拆分组合问题

### ISSUE THREAD

**Issue by remiliyaScarlet** [nihaojob/vue-fabric-editor#272]
![image](https://github.com/nihaojob/vue-fabric-editor/assets/38554772/eaf927fa-e682-4b03-baff-465de3746195)
先调用toActiveSelection会导致后面getObjects的数组是空的，拆分完毕id还是一样的
![image](https://github.com/nihaojob/vue-fabric-editor/assets/38554772/cbbefc49-706c-4990-9d9b-e958b6e819b4)
我改成这样了，就解决了

**Comment by nihaojob** [comment]
已修复，感谢反馈
https://github.com/nihaojob/vue-fabric-editor/commit/e99632470874a11830dbbd857ca6621ab2041c35
