### ISSUE TITLE
社区其他版本 SDK版、electron版、React版、Element版、Vue2版、PSD导入

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#282]
- SDK优化版 https://github.com/Smi1e96/vue-fabric-editor/tree/f-monorepo
- electron版 https://github.com/Qiu-Jun/electron-fabric-editor
- 稿定版 https://github.com/haixin-fang/vue-design-editor
- fabric  V6版本 https://github.com/dromara/yft-design
- React版 https://github.com/x007xyz/r-fabric-editor
- Element版 支持PSD  https://github.com/LvHuaiSheng/vue-fabric-editor-element
- vue2版本 https://github.com/nihaojob/vue-fabric-editor/releases/tag/vue

**Comment by more-strive** [comment]
V6版本：https://github.com/dromara/yft-design
![clipper](https://github.com/nihaojob/vue-fabric-editor/assets/113762408/3dab052d-4b22-4312-aa7d-9a8488166330)
