### ISSUE TITLE
selling this code 

### ISSUE THREAD

**Issue by iqbalcrat** [nihaojob/vue-fabric-editor#283]
Hello I found an YouTube video where he is selling this code for money 

https://www.youtube.com/watch?v=C_px3Js_Ucw&lc=UgwnrOYReDeaiYGJ8L14AaABAg.9w_QYYCiByE9w_bJfZeMl1

**Comment by nihaojob** [comment]
> Hello I found an YouTube video where he is selling this code for money
> 
> https://www.youtube.com/watch?v=C_px3Js_Ucw&lc=UgwnrOYReDeaiYGJ8L14AaABAg.9w_QYYCiByE9w_bJfZeMl1

谢谢你的提醒，我的账号在youtube无法评论了，期望有善良的开发者能够在评论中留下开源项目地址，并告诉大家这个项目的使用是免费开源的。


Thank you for reminding me that my account cannot be commented on youtube. I hope some kind developers can leave the open source project address in the comments and tell everyone that the use of this project is free and open source.

**Comment by darwin-buelo** [comment]
Hi I have leave a comment with the link to the repository and the demo site.

**Comment by darwin-buelo** [comment]
> Hi I have leave a comment with the link to the repository and the demo site.

Seems like He hide my comment. lol

**Comment by nihaojob** [comment]
> > Hi I have leave a comment with the link to the repository and the demo site.
> 
> Seems like He hide my comment. lol

嗨，谢谢你的举措，我也不确定有什么办法能够让他不隐藏，信息不对称让他产生了利润，不过侧面这个项目还是有一点点价值的 哈哈。

Hi, thank you for your move, I'm not sure there is any way to make him not hide, information asymmetry makes him generate profits, but the side of this project is still a little bit of value haha.

**Comment by nihaojob** [comment]
<img width="1027" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/13534626/e2b4004e-0e1b-4fd8-8480-a3e9562dea57">
