### ISSUE TITLE
如何使用 2 个画布

### ISSUE THREAD

**Issue by datpvnal** [nihaojob/vue-fabric-editor#287]
我希望能够创建多个页面并根据每个页面编辑画布

**Comment by datpvnal** [comment]
@nihaojob I'm developing this project and want to use 2 to 3 canvases, can you guide me? Thank you very much.

**Comment by nihaojob** [comment]
> @nihaojob I'm developing this project and want to use 2 to 3 canvases, can you guide me? Thank you very much.

我们正在写作一份关于编辑器的付费专栏教程，如果你感兴趣可以加我微信，我们后续会发布到网络上。

**Comment by SunInLifeStart** [comment]
+1
