### ISSUE TITLE
建议加入真正的描边

### ISSUE THREAD

**Issue by ljjsimon** [nihaojob/vue-fabric-editor#292]
现在的描边是那个「阴影」功能吗？如果四周都要的话，就必须选择模糊，但是我有不想要模糊。就是真正的描边

**Comment by nihaojob** [comment]
> 现在的描边是那个「阴影」功能吗？如果四周都要的话，就必须选择模糊，但是我有不想要模糊。就是真正的描边

这是2个独立的功能 
![image](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/6d7d2016-f65d-4b31-ae37-7687663470bd)

**Comment by ljjsimon** [comment]
@nihaojob 如果是背景透明的图的话，边框会加载矩形的边缘，阴影加在人物的边缘。我需要的「描边」是加在人物边缘一圈。
![WX20231121-131248@2x](https://github.com/nihaojob/vue-fabric-editor/assets/1535231/cf9158c5-1d75-44c0-aed6-243883ca2428)
也就是这张图里的红色一圈
![Uploading 截屏2023-11-21 13.17.06.png…]()

**Comment by nihaojob** [comment]
暂时不打算添加这样的功能，不确定这样的应用场景到底有多少，这个功能也比较麻烦
