### ISSUE TITLE
生成的图片左侧和上边会有1像素的模糊半透明细线

### ISSUE THREAD

**Issue by qyleenet** [nihaojob/vue-fabric-editor#296]
可将生成的图片放大查看，或拖拽到chrome中查看，会发现左侧和上面有大概1px细线，右边和下边正常

**Comment by mengkong123** [comment]
我在workspacePlugin.ts 中初始化的时候，设置 strokeWidth: 0 好像解决了，可以试试

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/bf19d9f293f1a6e8d9eb3ba3ae9014ad5b0f82ee
