### ISSUE TITLE
history组件，回退和重做好像没有按照步骤正常加载。

### ISSUE THREAD

**Issue by noob-Jp** [nihaojob/vue-fabric-editor#304]
当回退到初始状态时，在 [预览页面](https://nihaojob.github.io/vue-fabric-editor/#/) 的效果时，画布消失。
操作步骤：
1.添加两个基础元素
2.点击历史组件中的回退图标，

**Comment by nihaojob** [comment]
> 当回退到初始状态时，在 [预览页面](https://nihaojob.github.io/vue-fabric-editor/#/) 的效果时，画布消失。 操作步骤： 1.添加两个基础元素 2.点击历史组件中的回退图标，

我们正在用新的方式实现历史记录的功能，见PR：
https://github.com/nihaojob/vue-fabric-editor/pull/311

**Comment by nihaojob** [comment]
已修复  https://github.com/nihaojob/vue-fabric-editor/pull/311
