### ISSUE TITLE
路由跳转报错

### ISSUE THREAD

**Issue by loginleng** [nihaojob/vue-fabric-editor#310]
使用的是vue-router:4.3.0版本；
我在画布home/index.vue文件中增加了一个方法：
const goback = () => {
  router.push({ name: 'TemplateControl' });
};
触发该方法链接改变了，却没有跳转。
![1709543983980](https://github.com/nihaojob/vue-fabric-editor/assets/87188190/64080422-500f-48df-9af2-15fa1abf4b4c)

**Comment by Qiu-Jun** [comment]
这个路由问题和这个仓库代码没啥关系吧，我貌似记得这个项目路由就一个home页面的，你看看自己添加的页面路由配置是否正确

**Comment by loginleng** [comment]
![1709602628001](https://github.com/nihaojob/vue-fabric-editor/assets/87188190/ebe0ec1b-312e-440d-a6fb-854291d9409f)
把方法传递进去，能解决销毁报错，路由也能跳转了
