### ISSUE TITLE
点击左右侧菜单时，画布的大小会恢复默认

### ISSUE THREAD

**Issue by dylanZk1** [nihaojob/vue-fabric-editor#312]

**Comment by dylanZk1** [comment]
经过排查，发现当把 WorkSpacePlugin.ts 中 auto 方法注释掉后就不会出现。建议修改一下auto方法的调用方式

**Comment by nihaojob** [comment]
> 经过排查，发现当把 WorkSpacePlugin.ts 中 auto 方法注释掉后就不会出现。建议修改一下auto方法的调用方式

是的 特意做的适配 当画布的父元素尺寸发生变化后，会自动适配大小
