### ISSUE TITLE
SVG导入时不规则路径剪切问题

### ISSUE THREAD

**Issue by louiesun** [nihaojob/vue-fabric-editor#325]
**Describe the bug**
SVG导入时透明图片背景变为黑色。
最小化svg出错样例：
[link](https://www.jianguoyun.com/p/DVhpteAQxMbiChj36soFIAA)
可以看到，预览是正常的

有趣的是，该svg是由MuPDF将pdf页面转成的svg。

**To Reproduce**
1. 把上述svg导入
2. See error

**Expected behavior**
正如Chromium核自带的预览。

**Screenshots**
![screenshot](https://s3.bmp.ovh/imgs/2024/04/10/d154a6f0ff274bb8.png)

**Desktop (please complete the following information):**
 - Chromium
 - Version The official sample(github.io)

**Additional Text**
八成是透明黑？
即RGBA色值中，透明一般采用`（255,255,255,0）`
我正在构思使用MuPDF+Fabricjs写一个PDF编辑器。

**Comment by nihaojob** [comment]
@louiesun 我尝试使用项目里的SVG图片，并没有发生变黑的情况，你可以用下边的这个SVG图片试下
https://nihaojob.github.io/vue-fabric-editor-static/svg/387.svg

**Comment by nihaojob** [comment]
@louiesun 暂时还没计划哈
