### ISSUE TITLE
ESLint couldn't find the config "./.eslintrc-auto-import.json" 

### ISSUE THREAD

**Issue by AliceLanniste** [nihaojob/vue-fabric-editor#329]
**Describe the bug**
我提交pr的时候出现这个问题
<img width="793" alt="屏幕截图 2024-04-12 161749" src="https://github.com/nihaojob/vue-fabric-editor/assets/17617116/63dcdaa9-5264-4f58-9f46-163278ad1966">

**To Reproduce**
git commit -m 'xxxx'

**Desktop (please complete the following information):**
OS: windows11 -wsl2

**Comment by nihaojob** [comment]
https://nihaojob.github.io/editorDoc/guide/community.html 
感谢你能为为项目做出贡献，可以看下贡献指南中 commit 的部分

**Comment by AliceLanniste** [comment]
谢谢你的回答，我看了贡献指南，没明白那个格式是什么意思。是必须写body和footer吗。下面截图是我写的commit msg
![image](https://github.com/nihaojob/vue-fabric-editor/assets/17617116/5ef2b139-bfc1-4673-a751-8f46e11e6cb0)

**Comment by nihaojob** [comment]
这是一个通用的commit msg 提价规范，你可以从这里边获得详细的信息。
https://www.conventionalcommits.org/zh-hans/v1.0.0/#%e7%ba%a6%e5%ae%9a%e5%bc%8f%e6%8f%90%e4%ba%a4%e8%a7%84%e8%8c%83


你可以参考历史提交的commit 格式：fix(添加SVG元素): 元素自动适配画布大小

**Comment by AliceLanniste** [comment]
谢谢你的建议，我安装你的建议写了个符合格式的 commit。
![image](https://github.com/nihaojob/vue-fabric-editor/assets/17617116/e5ef81fa-176d-4c98-b8a3-c8a99dc8b78c)

但是还是提交失败了：
![image](https://github.com/nihaojob/vue-fabric-editor/assets/17617116/fa2bba2a-2803-4360-8500-a94381cb06fd)
这张图显示我在`eslint --fix` 失败了。可能是因为这个导致我没法提交。

**Comment by AliceLanniste** [comment]
当我把`.eslintrc.json`这条注释之后，就能顺利提交了。
这条配置信息建议删除
![image](https://github.com/nihaojob/vue-fabric-editor/assets/17617116/7682e756-4d94-47de-98d2-d9726041dce6)

**Comment by Qiu-Jun** [comment]
> 当我把`.eslintrc.json`这条注释之后，就能顺利提交了。
> 
> 这条配置信息建议删除
> 
> ![image](https://github.com/nihaojob/vue-fabric-editor/assets/17617116/7682e756-4d94-47de-98d2-d9726041dce6)
> 
> 

你有把项目跑起来吗，正常跑起来就会生成那个json文
