### ISSUE TITLE
历史记录后退导致的图层面板图层数量与元素不一致

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#334]
**Describe the bug**
向画布中添加2个元素，然后执行历史记录的撤销和前进操作，操作后，图层面板中的图层变成了一个。

![image](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/faac4a12-bf76-4856-9a59-25c7218d93d6)

**Comment by AliceLanniste** [comment]
这个我想试一试

**Comment by nihaojob** [comment]
@AliceLanniste 我定位到可能和fabric-history 的 这行代码有关系，https://github.com/alimozdemir/fabric-history/blob/master/src/index.js#L27C1-L28C1，

因为vue-fabric-editor 给元素增加了一些自定义属性，但是fabric-history不会对这些属性做处理，导致我们添加的自定义属性丢失

**Comment by nihaojob** [comment]
> 这个我想试一试

因为这历史就影响到了我其他项目的使用，比较着急，我就先自己修复了哈 
https://github.com/nihaojob/vue-fabric-editor/commits/main/
