### ISSUE TITLE
给文字设置边框和阴影的颜色，第一次不生效，要点击空白后第二次设置才行。

### ISSUE THREAD

**Issue by ijry** [nihaojob/vue-fabric-editor#346]
官方Demo可复现，选任何颜色，第一次会变成黑色。
<img width="766" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/3102798/14a273c4-b889-4615-88f6-2dc2b967f82d">

**Comment by Qiu-Jun** [comment]
感谢反馈
