### ISSUE TITLE
右侧ColorPicker颜色选择器手动输入颜色后设置失效

### ISSUE THREAD

**Issue by wuchenguang1998** [nihaojob/vue-fabric-editor#362]
右侧的颜色选择器，如果是手动输入颜色值，点击确定，并没有设置成功
![微信截图_20240504132019](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/b0cc3252-4c74-4fd0-9928-16ba19b4662f)
另外发现配置水印的颜色也有一样的问题
![微信截图_20240504132253](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/b96c2807-33fd-4f4e-9591-72b480372d21)

**Comment by wuchenguang1998** [comment]
已提交PR修复此问题

**Comment by Qiu-Jun** [comment]
> 已提交PR修复此问题

已合并
