### ISSUE TITLE
控制台警告可能出现内存泄露

### ISSUE THREAD

**Issue by wuchenguang1998** [nihaojob/vue-fabric-editor#364]
![微信截图_20240504155521](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/73032d0e-4646-49f9-94dd-c08ce1dab0e0)

**Comment by wuchenguang1998** [comment]
已提交PR修复此问题

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/365
