### ISSUE TITLE
点击元素与图层无法对应

### ISSUE THREAD

**Issue by wuchenguang1998** [nihaojob/vue-fabric-editor#369]
导入第二个模板，在图层栏只有3个元素，但实际在画布中的元素不止3个，于是会出现点击不同的元素，左边的图层栏高亮的都是同一个元素的问题。元素与图层无法对应上，导致点击图层栏的子项时，选不到想要的元素。
![image](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/0935e19f-224b-49b3-bd16-e07df462857d)
![image](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/0eb0aa8f-643f-43bf-b3a2-3d994924bf2c)
试了其他一些模板，也有这个问题。
实际期待的效果：画布中的元素都能与图层栏的每一项对应上。

**Comment by wuchenguang1998** [comment]
已提交PR修复此问题

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/371
