### ISSUE TITLE
箭头放缩变形及比例不一致

### ISSUE THREAD

**Issue by wuchenguang1998** [nihaojob/vue-fabric-editor#372]
在画布中绘制箭头时，有两个问题：
1.绘制箭头后，箭头端是正常形状，再点击箭头线后去拉伸调整尺寸，此时箭头端的形状因为拉伸而发生变形。
![微信截图_20240508232329](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/501ea5fb-867d-40cc-803c-a2ccf1791ed6)
2.绘制箭头后，在右侧调整边框宽度，发现只有箭头线变宽，箭头端还是原来大小，导致箭头比例很奇怪。
![微信截图_20240508232716](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/f830b5a6-ea55-40d7-81ae-94be3597e290)
![微信截图_20240508232750](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/4e0a6602-cc79-4d63-a66b-14c778f9b1c0)

**Comment by wuchenguang1998** [comment]
已提交PR修复此问题

**Comment by Qiu-Jun** [comment]
> 已提交PR修复此问题

已合并

**Comment by nihaojob** [comment]
大佬效率了 👍🏻👍🏻👍🏻

**Comment by wuchenguang1998** [comment]
> 大佬太效率了 👍🏻👍🏻👍🏻

哈哈刚好最近在研究这个
