### ISSUE TITLE
元素点击切换，边框属性值没有回填

### ISSUE THREAD

**Issue by wuchenguang1998** [nihaojob/vue-fabric-editor#375]
元素点击切换，右侧的边框属性值没有回填。
例如：先在画布中添加三角形，边框颜色为红色，宽度为10，边框样式为Dash-3；然后添加圆形，边框颜色为蓝色，宽度为5，边框样式为Stroke。点击元素来回切换，右侧的边框颜色和宽度都是正常回填，但边框样式却没回填到。
***
点击圆形的效果：
![微信截图_20240509232310](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/1ab40c53-05fe-4342-8ede-2930fb69053d)
***
点击三角形的效果：
![微信截图_20240509232235](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/91c4b270-53ca-4ef4-afa3-b4a0d627216b)

**Comment by wuchenguang1998** [comment]
已提交PR修复此问题

**Comment by nihaojob** [comment]
感谢大佬，已经合并到主分支  https://github.com/nihaojob/vue-fabric-editor/pull/376
