### ISSUE TITLE
背景尺寸设置

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#41]
1. 能够设置尺寸，不会超出画布
2. 画布放大缩小流畅
3. 画布大小可保存

**Comment by nihaojob** [comment]
思路1  找到偏移的中心点，缩放后正好在中间，1步到位。
思路2  设置画布大小后，调整所有元素到中间位置。

**Comment by ruanhuishi** [comment]
建议参考类似 ，jQueryui-ruler  防PS界面屏幕标尺插件；微信发你

**Comment by ruanhuishi** [comment]
插件

**Comment by nihaojob** [comment]
> 建议参考类似 ，jQueryui-ruler 防PS界面屏幕标尺插件；微信发你

已收到代码，非常感谢，ruler的功能后期加上，目前缩放已实现。
