### ISSUE TITLE
点击时会有红色箭头

### ISSUE THREAD

**Issue by AliceLanniste** [nihaojob/vue-fabric-editor#420]
**Describe the bug**

https://github.com/nihaojob/vue-fabric-editor/assets/17617116/85b3921a-f2ae-4814-b968-008d108d92b4

**Expected behavior**
当切换成文字和素材点击的时候应该没有红色箭头

**Comment by wuchenguang1998** [comment]
绘制元素的6个类型都有这个情况
算是优化点，已提交解决(#422)。

**Comment by AliceLanniste** [comment]
<img width="601" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/17617116/b2174d53-ea87-44d7-8562-181800550c90">
并没有解决，当使用绘制元素绘制完成后，点击鼠标仍然 出现箭头的

**Comment by wuchenguang1998** [comment]
@AliceLanniste 因为还处于绘制状态，绘制一条之后还可以接着绘制
如果要取消绘制状态可以点击右侧对应项
![image](https://github.com/nihaojob/vue-fabric-editor/assets/63847336/35e2131c-667a-45a3-a907-6c05415c0146)
或者切换文字、素材等栏目，也可以取消绘制状态
