### ISSUE TITLE
裁切后组合裁切的内容会出错

### ISSUE THREAD

**Issue by fixjie** [nihaojob/vue-fabric-editor#423]
图片添加裁切后和其它东西组合后，图片的裁切会被改变

**Comment by fixjie** [comment]
Uploading QQ202467-94312.mp4…

**Comment by fixjie** [comment]
https://github.com/nihaojob/vue-fabric-editor/assets/50942819/365e87d5-ebef-43fa-b179-7e5dca5c45b7

**Comment by ByeWord** [comment]
> QQ202467-94312.mp4

已经修复，等项目管理们合并代码
