### ISSUE TITLE
组元素隐藏描边选项

### ISSUE THREAD

**Issue by nihaojob** [nihaojob/vue-fabric-editor#433]
组元素隐藏描边选项

**Comment by AliceLanniste** [comment]
这个我想试试，能不能具体说说什么情况

**Comment by nihaojob** [comment]
> 这个我想试试，能不能具体说说什么情况

可以在画布中添加2个元素，然后选中两个变成组合，变成组合选中后，不应该出现 边框选项，可以看下边框组件里的判断条件，只有是支持类型时再展示

![image](https://github.com/nihaojob/vue-fabric-editor/assets/13534626/0f7d23c4-52a1-4a46-86f9-73fb90df4776)
