### ISSUE TITLE
透明图像颜色选择器样式优化

### ISSUE THREAD

**Issue by Qiu-Jun** [nihaojob/vue-fabric-editor#444]
弹层位置导致确认按钮被超出了边界
![20240619115741](https://github.com/nihaojob/vue-fabric-editor/assets/24954362/c4222f09-1ef2-4da5-8af8-ce0af48cdd2c)

**Comment by AliceLanniste** [comment]
这个我来试试

**Comment by AliceLanniste** [comment]
@Qiu-Jun ，你好我定位到这个颜色选择器，可是没有看到有弹层的组件或者逻辑，
<img width="521" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/17617116/3f48439c-0a89-4366-95c1-9e2870bfaeb4">

**Comment by Qiu-Jun** [comment]
> @Qiu-Jun ，你好我定位到这个颜色选择器，可是没有看到有弹层的组件或者逻辑，可是在Color-picker/index.vue没有找到弹层
> 
> <img width="521" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/17617116/3f48439c-0a89-4366-95c1-9e2870bfaeb4">
> 
> 

这个应该是iview 的tooltip组件，他出现的位置在这个元素的下中，而元素靠右导致这个问题

**Comment by Qiu-Jun** [comment]
> @Qiu-Jun ，你好我定位到这个颜色选择器，可是没有看到有弹层的组件或者逻辑，可是在Color-picker/index.vue没有找到弹层
> 
> <img width="521" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/17617116/3f48439c-0a89-4366-95c1-9e2870bfaeb4">
> 
> 
把那个tooltip设置到左边也行，不遮挡就ok

**Comment by AliceLanniste** [comment]
晕这个原来是iview自带的色彩选择器，我一直以为是自定义，找了半天都没对上号

**Comment by Qiu-Jun** [comment]
> @Qiu-Jun ，你好我定位到这个颜色选择器，可是没有看到有弹层的组件或者逻辑，可是在Color-picker/index.vue没有找到弹层 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/17617116/342282492-3f48439c-0a89-4366-95c1-9e2870bfaeb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODU5MzcsIm5iZiI6MTcxOTI4NTYzNywicGF0aCI6Ii8xNzYxNzExNi8zNDIyODI0OTItM2Y0ODQzOWMtMGE4OS00MzY2LTk1YzEtOWUyODcwYmZhZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAzMjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MmY2MWJiZjY1YmE4ZDliM2JiZTE5NTQ2OGY5MTc3ZTg3NWQwZmU0NjNjZjg5YzhhMDVmZjJhNjY4NGE4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPGN8US3PurkJpfu3vdunvI4L2uXSMTfV3wQLPrTWnA">

sorry，我记错了。  最近有个bug用的是文件渐变那边好像用的是tooltip处理的弹层。搞混了。删下console再提交下
