### ISSUE TITLE
文本颜色无法修改

### ISSUE THREAD

**Issue by SamCheng0717** [nihaojob/vue-fabric-editor#447]
## 问题1
1. 基础要素点击字体添加到画布
2. 点击颜色，在输入框站体#653fe2ff，点击颜色输入框旁边的位置
3. 可以看到，颜色改动了，字体颜色并没有改动，预期与实际不一致。
## 问题2
选择字体【阿里巴巴普惠体Heavy】后，修改字号为120，字号不可见。建议缩短前面的字体选择框。

**Comment by Qiu-Jun** [comment]
问题已确认：
问题1： 输入颜色改变没有触发对应的方法，具体没有查看
问题2： 弹出位置问题，被遮挡，样式优化即可

**Comment by Qiu-Jun** [comment]
> ## 问题1
> 1. 基础要素点击字体添加到画布
> 2. 点击颜色，在输入框站体#653fe2ff，点击颜色输入框旁边的位置
> 3. 可以看到，颜色改动了，字体颜色并没有改动，预期与实际不一致。
> 
> ## 问题2
> 选择字体【阿里巴巴普惠体Heavy】后，修改字号为120，字号不可见。建议缩短前面的字体选择框。

秦大佬那边已经更换了颜色渐变器
