### ISSUE TITLE
接口全部401了

### ISSUE THREAD

**Issue by 24623253** [nihaojob/vue-fabric-editor#453]
![微信截图_20240628143151](https://github.com/nihaojob/vue-fabric-editor/assets/41353019/ede2dd60-977e-4382-8244-0033c9c01130)

**Comment by 24623253** [comment]
以为是过期等问题，清除缓存后接口依然401

**Comment by nihaojob** [comment]
感谢反馈 已恢复了哈 mysql挂了 重启了
