### ISSUE TITLE
建议移除@kuaitu/core中view-ui-plus的Message方法引入

### ISSUE THREAD

**Issue by momo2019** [nihaojob/vue-fabric-editor#459]
文件位置packages/core/utils/utils.ts中使用了view-ui-plus的Message方法。
具体使用位置在clipboardText方法中。

建议将提示Message放在业务层，方便仅引入@kuaitu/core的使用者

<img width="767" alt="image" src="https://github.com/nihaojob/vue-fabric-editor/assets/26078793/a44852bd-5d17-44bf-a1e0-58245698a9f6">

**Comment by nihaojob** [comment]
很好的建议哈  修改应该不会花太多时间，大佬有时间的话，欢迎PR到项目哈

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/460
