### ISSUE TITLE
撤销会导致清空画板

### ISSUE THREAD

**Issue by dingh123** [nihaojob/vue-fabric-editor#475]
重现步骤：
1、添加模版到画布
2、操作一下画板任意元素，
3、点击撤销

这个时候，画板就被清空了，应该是还原画板到模版初始状态

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/commit/e57fa80e5fea4273e7f074f0e060fd95d6705e14

已修复哈
