### ISSUE TITLE
输入文本能否自动换行

### ISSUE THREAD

**Issue by x1nGoo** [nihaojob/vue-fabric-editor#5]
输入的文本超出画布大小时能否自动换行?

**Comment by nihaojob** [comment]
> 

可以使用基础元素里第二个text元素，会指定区域宽度，超过后会自动换行。

**Comment by nihaojob** [comment]
> 输入的文本超出画布大小时能否自动换行?

可以使用基础元素里第二个text元素，会指定区域宽度，超过后会自动换行。
