### ISSUE TITLE
是否考虑支持nuxt?

### ISSUE THREAD

**Issue by jiangming96** [nihaojob/vue-fabric-editor#50]
请问是否考虑支持ssr以及发布成独立的npm包

**Comment by nihaojob** [comment]
是有什么场景需要吗？ 欢迎一起讨论哈

**Comment by jiangming96** [comment]
@nihaojob 是这样的，在有些项目需要ssr，vue的ssr有一种方案是nuxtjs，在nuxtjs区分server和client的，nuxtjs在server渲染的时候是没有window等一些其他对象的会出现一些错误，所以想问下是否考虑支持nuxtjs？关于发布成独立npm包这样自由度会更高开发者可以自由发挥的空间更大

**Comment by nihaojob** [comment]
@jiangming96 感谢详细的描述，我对ssr接触的不多，也没有商业图片编辑器项目的经验，只是个人兴趣开发的一款图片编辑器，但是希望能够满足更多的场景并持续迭代。
关于上边的两个问题，我是这样理解的：
1. 先有SDK，再有是否支持nuxtjs的问题；如果没有SDK，支持nuxtjs可能就是把这个项目的代码粘到nuxtjs中去，还是按照客户端渲染的形式使用。
2. 我没有使用过其他例如稿定、美图秀秀的编辑器的SDK，我需要先学习使用他们的SDK，才知道如何设计SDK的接口；如果你有明确的需求或者意愿强烈，欢迎一起讨论实现。
3. 目前的架构趋向于把功能代码和组件分开，如在现有基础上将编辑器打包为SDK的改造工作量可能并不会特别大。

**Comment by jiangming96** [comment]
@nihaojob 好的，加油！期待功能更加完善。
