### ISSUE TITLE
能否添加自动感知周边对象功能

### ISSUE THREAD

**Issue by redxman** [nihaojob/vue-fabric-editor#6]
自动感知周边对象，可以进行移动对齐等操作

**Comment by nihaojob** [comment]
> 自动感知周边对象，可以进行移动对齐等操作

可以实现的，辅助线和自动对齐、吸附功能，感兴趣一起开发呀 哈哈

**Comment by nihaojob** [comment]
辅助线方法参考：https://my.oschina.net/xmqywx/blog/1941539

**Comment by nihaojob** [comment]
> 自动感知周边对象，可以进行移动对齐等操作

https://github.com/nihaojob/vue-fabric-editor/pull/19  已更新
