### ISSUE TITLE
透明图片画布背景问题

### ISSUE THREAD

**Issue by macheteHot** [nihaojob/vue-fabric-editor#62]
使用矩形模拟画布 对于白色背景或透明图片的处理并不友好 应当像ps 背景层一样有棋盘格子 并附有拖拽效果
如果有此需求愿意贡献代码
![dd](https://user-images.githubusercontent.com/26652329/219155137-6e60ef6e-2047-4504-a657-08c556549484.gif)

**Comment by nihaojob** [comment]
你的项目好棒，很细腻，背景透明和标尺是f非常需要的功能，如果大佬能够提供PR或者思路就太好了。

1. 网格背景问题：我目前的实现方式是给css设置了一个网格背景图片，效果不是特别好，被我注释掉了。
https://github.com/nihaojob/vue-fabric-editor/blob/af13aecc10b6e152928208e70351346596686d50/src/views/home/index.vue#L214-L220

2. 关于背景透明的问题，目前使用的是iview的ColorPicker，还不支持透明色的选择。

期待大佬的PR，或者加微信一起交流哈：13146890191
