### ISSUE TITLE
组合定位问题

### ISSUE THREAD

**Issue by Me20201996** [nihaojob/vue-fabric-editor#7]
请教一个问题，当两个元素(矩形+文字)组合的时候，整体的位置(x, y)是正值，而组合的元素(矩形和文字)的left、top都是负值，组合后的子元素都是根据什么定位的？

**Comment by nihaojob** [comment]
没太明白是什么问题，有详细的信息吗

**Comment by Me20201996** [comment]
你好 ，我要做的是一个图片标注的功能，鼠标绘制矩形(矩形中显示文字)，绘制完之后可以提交相关的数据（位置等信息）用于提高模型精度。




Me
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nihaojob/vue-fabric-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月27日(星期四) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nihaojob/vue-fabric-editor] 组合定位问题 (Issue #7)





 
没太明白是什么问题，有详细的信息吗

**Comment by Me20201996** [comment]
现在的问题是：我矩形+文字的显示使用了group组合，组合后会导致rect和text的位置信息有偏差。这个位置问题？还有就是大神有没有什么好的可以做图片标注的插件推荐。可以给点建议吗？万分感谢



Me
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nihaojob/vue-fabric-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月27日(星期四) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nihaojob/vue-fabric-editor] 组合定位问题 (Issue #7)





 
没太明白是什么问题，有详细的信息吗

**Comment by Me20201996** [comment]
> 没太明白是什么问题，有详细的信息吗

你好 ，我要做的是一个图片标注的功能，鼠标绘制矩形(矩形中显示文字)，绘制完之后可以提交相关的数据（位置等信息）用于提高模型精度。现在的问题是：我矩形+文字的显示使用了group组合，组合后会导致rect和text的位置信息有偏差。这个位置问题？还有就是大神有没有什么好的可以做图片标注的插件推荐。可以给点建议吗？万分感谢

**Comment by nihaojob** [comment]
> > 没太明白是什么问题，有详细的信息吗
> 
> 你好 ，我要做的是一个图片标注的功能，鼠标绘制矩形(矩形中显示文字)，绘制完之后可以提交相关的数据（位置等信息）用于提高模型精度。现在的问题是：我矩形+文字的显示使用了group组合，组合后会导致rect和text的位置信息有偏差。这个位置问题？还有就是大神有没有什么好的可以做图片标注的插件推荐。可以给点建议吗？万分感谢

https://github.com/OvidijusParsiunas/myvision  找到一个基于fabric的图片标注工具，可以看下
