### ISSUE TITLE
进行一次撤销操作后，背景图层可以进行删除

### ISSUE THREAD

**Issue by hudenghui** [nihaojob/vue-fabric-editor#74]
![20230222160513](https://user-images.githubusercontent.com/17875293/220559936-4e5ae607-2d0f-43e0-8f68-de8abdf28b84.png)

**Comment by nihaojob** [comment]
> ![20230222160513](https://user-images.githubusercontent.com/17875293/220559936-4e5ae607-2d0f-43e0-8f68-de8abdf28b84.png)

感谢反馈，我晚些看下，应该是回退后没有把模拟画布的矩形锁定。

bug位置：
https://github.com/nihaojob/vue-fabric-editor/blob/b109825b765147633731c6c6fd8368865b852f1c/src/components/history.vue#L73-L77

参考实现：
https://github.com/nihaojob/vue-fabric-editor/blob/b109825b765147633731c6c6fd8368865b852f1c/src/components/importTmpl.vue#L59-L67

根本的问题是，没有处理好全局的 'workspace' 对象问题。

**Comment by nihaojob** [comment]
https://github.com/nihaojob/vue-fabric-editor/pull/75
